"""Add layout fields to question model

Revision ID: 8af457bb0b8c
Revises: 20260608_0002
Create Date: 2026-06-08 13:40:29.050685
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8af457bb0b8c'
down_revision = '20260608_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_answers_response_question', 'answers', type_='unique')
    op.add_column('questions', sa.Column('position_x', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('questions', sa.Column('position_y', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('questions', sa.Column('is_start_node', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index('ix_survey_assignments_status', table_name='survey_assignments')
    op.drop_constraint('uq_survey_assignments_survey_user', 'survey_assignments', type_='unique')
    op.drop_index('ix_survey_responses_status', table_name='survey_responses')
    op.drop_index('ix_surveys_created_by_id', table_name='surveys')
    op.drop_index('ix_surveys_status', table_name='surveys')
    op.drop_constraint('uq_users_phone', 'users', type_='unique')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_unique_constraint('uq_users_phone', 'users', ['phone'])
    op.create_index('ix_surveys_status', 'surveys', ['status'], unique=False)
    op.create_index('ix_surveys_created_by_id', 'surveys', ['created_by_id'], unique=False)
    op.create_index('ix_survey_responses_status', 'survey_responses', ['status'], unique=False)
    op.create_unique_constraint('uq_survey_assignments_survey_user', 'survey_assignments', ['survey_id', 'user_id'])
    op.create_index('ix_survey_assignments_status', 'survey_assignments', ['status'], unique=False)
    op.drop_column('questions', 'is_start_node')
    op.drop_column('questions', 'position_y')
    op.drop_column('questions', 'position_x')
    op.create_unique_constraint('uq_answers_response_question', 'answers', ['response_id', 'question_id'])
    # ### end Alembic commands ###

